### ISSUE TITLE
nc: Proxy error: "HTTP/1.1 200 Connection Established"

### ISSUE THREAD

**Issue by brianyaklin** [jamf/Jamf-Environment-Test#8]
The JAMF Environment Test requires a response with 'succeeded' being in the return string when running nc. Specifically, when a proxy is in use:
```
...
				STATUS=$(/usr/bin/nc -z -G 3 -x ${PROXY_HOST}:${PROXY_PORT} -X connect ${HOSTNAME} ${PORT} 2>&1 | /usr/bin/awk '{print $7}')
...
		if [[ ${STATUS} =~ "succeeded" ]]; then
			AVAILBILITY="succeeded"
		
		else
			AVAILBILITY="failed"
		fi
```

Unfortunately, the experience that we have seen is that the response through a proxy is raising an error even though its connection is established and we see an HTTP 200 on the proxy itself (10.1.1.1 is just a generic IP, but will represent the proxy in this example):
```
$ /usr/bin/nc -z -G3 -x 10.1.1.1:80 -X connect albert.apple.com 443
nc: Proxy error: "HTTP/1.1 200 Connection Established"
```

I haven't been able to identify why NC reports a proxy error but suspect its because of HTTP/1.1 being used. Additionally, the awk command used to identify the STATUS variable will be set to `Established"` with the double quote.

**Comment by daniel-maclaughlin** [comment]
Hi, 
I haven't been able to replicate this. when there is a successful connection the expected result is 
Connection to albert.apple.com port 443 [tcp/https] succeeded!
so the application is looking for if the last field matches succeeded, if not then I am returning an Unavailable flag in the table.

the response may be that you were able to talk to the proxy server correctly since we are using the -z flag for NC we aren't sending any data which may be the scenario that you are encountering. It may be more specific to your proxy and environment though
